# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: servo.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bservo.proto\x12\x08\x44oorLock\"\x0f\n\rUnlockRequest\"\r\n\x0bLockRequest\"!\n\x0eUnlockResponse\x12\x0f\n\x07success\x18\x01 \x01(\x05\"\x1f\n\x0cLockResponse\x12\x0f\n\x07success\x18\x01 \x01(\x05\x32\x82\x01\n\x08\x44oorLock\x12=\n\x06Unlock\x12\x17.DoorLock.UnlockRequest\x1a\x18.DoorLock.UnlockResponse\"\x00\x12\x37\n\x04Lock\x12\x15.DoorLock.LockRequest\x1a\x16.DoorLock.LockResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'servo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_UNLOCKREQUEST']._serialized_start=25
  _globals['_UNLOCKREQUEST']._serialized_end=40
  _globals['_LOCKREQUEST']._serialized_start=42
  _globals['_LOCKREQUEST']._serialized_end=55
  _globals['_UNLOCKRESPONSE']._serialized_start=57
  _globals['_UNLOCKRESPONSE']._serialized_end=90
  _globals['_LOCKRESPONSE']._serialized_start=92
  _globals['_LOCKRESPONSE']._serialized_end=123
  _globals['_DOORLOCK']._serialized_start=126
  _globals['_DOORLOCK']._serialized_end=256
# @@protoc_insertion_point(module_scope)
